In [1]:
import numpy as np
b = np.array([[1, 2], [3, 4]])
print(b)
# [[1 2]
#  [3 4]]
print(b.shape)    # (2, 2)


[[1 2]
 [3 4]]
(2, 2)


In [2]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix[1, 2])        # 输出 6
print(matrix.T)            # 转置
print(matrix @ matrix)     # 矩阵乘法


6
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [10]:
import numpy as np

x=np.array([200,17])

w1_1=np.array([1,2])
b1_1=np.array([-1])
z1_1=np.dot(w1_1,x)+b1_1
a1_1=1/(1+np.exp(-z1_1))
print(a1_1)

[1.]


In [13]:
w=np.array([
    [1,-3,5],
    [2,4,-6]
])
print(w)

[[ 1 -3  5]
 [ 2  4 -6]]


In [ ]:
import numpy as np
AT=np.array([[200,17]])
W=np.array([
    [1,-3,5],
    [2,4,-6],
    ])
b=np.array([[-1,1,2]])
def dense(AT,W,b):
    Z=np.matmul(AT,W)+b
    A_out=1/(1+np.exp(-Z))
    return A_out

print(dense(AT,W,b))

[[1.00000000e+000 2.45261912e-231 1.00000000e+000]]


In [6]:
# 60 -17_TensorFlow实现
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

model=Sequential([
    Dense(units=25,activation='sigmoid'),
    Dense(units=15, activation='sigmoid'),
    Dense(units=1,activation='sigmoid')
])
from tensorflow.keras.losses import BinaryCrossentropy
model.compile(loss=BinaryCrossentropy())
model.fit(X,Y,epochs=100)

NameError: name 'X' is not defined